name: Python Unit Test

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup pipenv
      uses: dschep/install-pipenv-action@v1
      run: |
        pipenv install
    - name: Test
      run: |
        cd server
        pipenv run python -m unittest discover